boned/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('productos.urls')),
    path('', include('laboratorio.urls')),
    path('', include('principios_activos.urls')),
]

productos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('productos', views.ListadoProducto, name='productos'),
    path('productos/crear', views.crear_producto, name='crear_producto'),
]

productos/models.py
from django.db import models

class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'producto'

productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'precio', 'stock']

        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del producto'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Descripción del producto', 'rows': 4}),
            'precio': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Precio del producto'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Stock disponible'}),
        }

    def clean_precio(self):
        precio = self.cleaned_data.get('precio')
        if precio <= 0:
            raise forms.ValidationError("El precio debe ser un número positivo.")
        return precio

productos/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from .models import Producto
from .forms import ProductoForm

def ListadoProducto(request):
    busqueda = request.GET.get('busqueda', '')

    if busqueda:
        productos = Producto.objects.filter(nombre__icontains=busqueda) | Producto.objects.filter(descripcion__icontains=busqueda)
    else:
        productos = Producto.objects.all()

    total_productos = productos.count()

    paginator = Paginator(productos, 10)

    page_number = request.GET.get('page')  # page es el parámetro de la URL
    page_obj = paginator.get_page(page_number)

    return render(request, 'listado_producto.html',  {'page_obj': page_obj,'total_productos': total_productos})

def crear_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('productos')  # Redirige a la lista de productos después de crear uno nuevo
        else:
            print(form)
    else:
        form = ProductoForm()

    errores = {field: form[field].errors for field in form.fields if form[field].errors}

    return render(request, 'crear_producto.html', {'form': form, 'errores': errores})

productos/templates/components/formulario_creacion_producto.html
{% load static %}

<div class="row">

    <div>
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Crear Nuevo Producto</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    {% csrf_token %}
                    <div class="col-lg-6 mb-3">
                        <label for="id_nombre" class="form-label">Nombre <span class="text-danger">*</span></label>
                        {{ form.nombre }}
                        {% if form.nombre.errors %}
                        {% for error in form.nombre.errors %}
                        <p class="text-danger">{{ error }}</p>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <div class="col-lg-6">
                        <div class="d-flex justify-content-between">
                            <label for="product-categories" class="form-label">Product Categories</label>
                            {% include 'components/boton-crear-principio-activo.html' %}
                        </div>
                        <select class="form-control" id="product-categories" data-choices data-choices-groups data-placeholder="Select Categories" name="choices-single-groups">
                            <option value="">Choose a categories</option>
                            <option value="Fashion">Fashion</option>
                            <option value="Electronics">Electronics</option>
                            <option value="Footwear">Footwear</option>
                            <option value="Sportswear">Sportswear</option>
                            <option value="Watches">Watches</option>
                            <option value="Furniture">Furniture</option>
                            <option value="Appliances">Appliances</option>
                            <option value="Headphones">Headphones</option>
                            <option value="Other Accessories">Other Accessories</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="mb-3 col-lg-12">
                        <label for="id_descripcion" class="form-label">Descripción <span class="text-danger">*</span></label>
                        {{ form.descripcion }}
                        {% if form.descripcion.errors %}
                        {% for error in form.descripcion.errors %}
                        <p>{{ error }}</p>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <label for="product-stock" class="form-label">Tag</label>
                        <select class="form-control" id="choices-multiple-remove-button" data-choices data-choices-removeItem name="choices-multiple-remove-button" multiple>
                            <option value="Fashion" selected>Fashion</option>
                            <option value="Electronics">Electronics</option>
                            <option value="Watches">Watches</option>
                            <option value="Headphones">Headphones</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Pricing Details</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-4">
                        <form>
                            <label for="product-price" class="form-label">Price</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text fs-20"><i class='bx bx-dollar'></i></span>
                                <input type="number" id="product-price" class="form-control" placeholder="000">
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <form>
                            <label for="product-discount" class="form-label">Discount</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text fs-20"><i class='bx bxs-discount'></i></span>
                                <input type="number" id="product-discount" class="form-control" placeholder="000">
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-4">
                        <form>
                            <label for="product-tex" class="form-label">Tex</label>
                            <div class="input-group mb-3">
                                <span class="input-group-text fs-20"><i class='bx bxs-file-txt'></i></span>
                                <input type="number" id="product-tex" class="form-control" placeholder="000">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Add Product Photo</h4>
            </div>
            <div class="card-body">
                <div class="dropzone bg-light-subtle py-5">
                    <div class="fallback">
                        <input name="file" type="file" multiple="multiple">
                    </div>
                    <div class="dz-message needsclick">
                        <i class="bx bx-cloud-upload fs-48 text-primary"></i>
                        <h3 class="mt-4">Drop your images here, or <span class="text-primary">click to browse</span>
                        </h3>
                        <span class="text-muted fs-13">
                            1600 x 1200 (4:3) recommended. PNG, JPG and GIF files are allowed
                        </span>
                    </div>
                </div>

                <ul class="list-unstyled mb-0" id="dropzone-preview">
                    <li class="mt-2" id="dropzone-preview-list">
                        <!-- This is used as the file preview template -->
                        <div class="border rounded">
                            <div class="d-flex p-2">
                                <div class="flex-shrink-0 me-3">
                                    <div class="avatar-sm bg-light rounded">
                                        <img data-dz-thumbnail class="img-fluid rounded d-block" src="#" alt="Dropzone-Image" />
                                    </div>
                                </div>
                                <div class="flex-grow-1">
                                    <div class="pt-1">
                                        <h5 class="fs-14 mb-1" data-dz-name>&</h5>
                                        <p class="fs-13 text-muted mb-0" data-dz-size></p>
                                        <strong class="error text-primary" data-dz-errormessage></strong>
                                    </div>
                                </div>
                                <div class="flex-shrink-0 ms-3">
                                    <button data-dz-remove class="btn btn-sm btn-primary">Delete</button>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
                <!-- end dropzon-preview -->
            </div>
        </div>
        <div class="p-3 bg-light mb-3 rounded">
            <div class="row justify-content-end g-2">
                <div class="col-lg-2">
                    <a href="#!" class="btn btn-outline-secondary w-100">Create Product</a>
                </div>
                <div class="col-lg-2">
                    <a href="#!" class="btn btn-primary w-100">Cancel</a>
                </div>
            </div>
        </div>
        </form>
    </div>
</div>
{% include 'components/formulario-creacion-principio-activo.html' %}